### PR TITLE
Added badges to README.md

### PR DESCRIPTION
**Pull request by EwyBoy**

### CODE REVIEW

**Comment by EwyBoy** [comment]
Added badges to the readme. You can preview by looking at it here:
https://github.com/EwyBoy/KSP-2-tools-and-mods/blob/main/README.md

**Comment by warior456** [comment]
Some things I would like you to address: 
-fix the links to actually link to the correct mods
-how do you make these buttons for new mods?

**Comment by EwyBoy** [comment]
Ops, messed up some of the links. Gonna make a fix.
Its just a badge.

`- [Mod](https://example.com/) by ModDev`

**Comment by EwyBoy** [comment]
Unsure why I get a merge conflicts now, but the links are all fixed.

**Comment by EwyBoy** [comment]
Okey its all fixed

**Comment by warior456** [comment]
After asking some people, they have voted against badges since they are harder to read, so sorry that your effort won't be merged. Still thank you for the suggestions

**Pull request closed without merging**
